###################################################################################
# Purpose       :   Install Certbot snapd and and create a cronjob certificate renew task
# Author        :   Luca Bassi
# Date          :   25.10.2023
# Version       :   1.1
# Dependencies  :   None
###################################################################################

- name: playbook_certbot_install 

#------------------------------------------------------------
#
# 0 – General Ansible configuration
#
#------------------------------------------------------------

  hosts: rp-ms.myftp.org

  become: yes
  tasks:

#------------------------------------------------------------
#
# 1 – Installation
#
#------------------------------------------------------------

    - name: Install Snapd Package
      apt: 
        name: snapd 
        update_cache: yes 
        state: latest      
   
    - name: "install snapd certbot"
      shell: "snap install --classic certbot"
      args:
        executable: /bin/bash
      register: result

    - name: setup nginx certbot command symlink
      file: 
        path: /usr/bin/certbot
        src: /snap/bin/certbot
        state: link 
        force: yes

#------------------------------------------------------------
#
# 2 – Configuration
#
#------------------------------------------------------------

    - name: "Create /etc/letsencrypt folder"
      file:
        path: "/etc/letsencrypt/"
        state: directory
        owner: root
        group: root
        mode: u=rwx,g=x,o=x
  

    - name: Register certbot
      shell: |
        certbot -n register --agree-tos --email l.bassi@hotmail.fr
        touch /etc/letsencrypt/.registered
      args:
        creates: /etc/letsencrypt/.registered
      tags:
        - nginx
        - certbot

    - name: Setup cronjob for renewal
      cron:
        name: certbot-renewal
        job: "/bin/bash -lc '/usr/local/bin/certbot -q renew'"
        minute: "0"
        hour: "14"
      tags:
        - nginx
        - certbot

#------------------------------------------------------------
#
# 3 – Reload services
#
#------------------------------------------------------------

    - name: "Reload Nginx config witjout restart"
      shell: "nginx -s reload"
      args:
        executable: /bin/bash
      register: result
      
    - name: Show result
      debug:
        msg: "{{ result }}"



